# Generated by Django 2.0.4 on 2018-08-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='Banco',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='Direccion',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='Material1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='Material2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='Material3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='Rut',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='bodegas',
            name='Hoja_de_Cargo',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='bodegas',
            name='Ubicacion',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='bodegueros',
            name='Nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='Nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='Nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_helper',
            name='Unid',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='Centro_de_Costo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='Documento',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='Solicitado_por',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
