# Generated by Django 2.0.4 on 2018-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BODEGAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.CharField(max_length=50)),
                ('Hoja_de_Cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BODEGUEROS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MATERIALES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PROVEEDORES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUDES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Vigencia', models.DateField()),
                ('Version', models.IntegerField()),
                ('Estado', models.IntegerField()),
                ('Centro_de_Costo', models.CharField(max_length=50)),
                ('Documento', models.CharField(max_length=10)),
                ('Solicitado_por', models.CharField(max_length=50)),
                ('Fecha_Solicitud', models.DateField()),
                ('Fecha_Requerida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUDES2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CC', models.IntegerField()),
                ('Sol', models.IntegerField()),
                ('Item', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Cant', models.IntegerField()),
                ('Unid', models.IntegerField()),
                ('Cert', models.CharField(max_length=10)),
                ('AoD', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
