# Generated by Django 2.0.4 on 2018-08-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180826_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.IntegerField(default=1)),
                ('Importe', models.IntegerField(default=0)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.PROVEEDORES')),
            ],
        ),
    ]
