# Generated by Django 2.0.4 on 2018-07-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180713_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SOLICITUDES2',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='AoD',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='CC',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='Cant',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='Cert',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='Descripcion',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='Item',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='Sol',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='Unid',
            field=models.IntegerField(default=None),
        ),
    ]
